name: 'Rickroll'
description: 'Rickroll when tests fail'
inputs:
  percentage:
    description: 'Percentage chance of rickroll'
    required: false
    default: '100'
runs:
  using: 'composite'
  steps:
    - name: Rickroll
      shell: bash
      run: |
        echo "🎵 NEVER GONNA GIVE YOU UP 🎵"
        curl --max-time 10 -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash || true
        echo ""
        echo "🎵 Tests failed! You've been rickrolled! 🎵"